// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4xWdTWx6rm9A72D5sl6LcgahuTicGLpE',
    appId: '1:135314969174:web:b727a5c87fed6f17d2e1f7',
    messagingSenderId: '135314969174',
    projectId: 'taxi-app-e2e8f',
    authDomain: 'taxi-app-e2e8f.firebaseapp.com',
    storageBucket: 'taxi-app-e2e8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJMcnZkDmrdh2beiK3MPEVK7GD5azI2fs',
    appId: '1:135314969174:android:9d5a07d584217e81d2e1f7',
    messagingSenderId: '135314969174',
    projectId: 'taxi-app-e2e8f',
    storageBucket: 'taxi-app-e2e8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADM0gugAQZB03KWDr6viwXQ_8fSM2imHM',
    appId: '1:135314969174:ios:a4d82ca13ca5ca0dd2e1f7',
    messagingSenderId: '135314969174',
    projectId: 'taxi-app-e2e8f',
    storageBucket: 'taxi-app-e2e8f.firebasestorage.app',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADM0gugAQZB03KWDr6viwXQ_8fSM2imHM',
    appId: '1:135314969174:ios:a4d82ca13ca5ca0dd2e1f7',
    messagingSenderId: '135314969174',
    projectId: 'taxi-app-e2e8f',
    storageBucket: 'taxi-app-e2e8f.firebasestorage.app',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4xWdTWx6rm9A72D5sl6LcgahuTicGLpE',
    appId: '1:135314969174:web:9be5d168fe8280ccd2e1f7',
    messagingSenderId: '135314969174',
    projectId: 'taxi-app-e2e8f',
    authDomain: 'taxi-app-e2e8f.firebaseapp.com',
    storageBucket: 'taxi-app-e2e8f.firebasestorage.app',
  );
}
